version: '3.8'
name: photo-portfolio
services:
  client:
    container_name: portfolio-client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: 'no'
    networks:
      - webappnetwork

  api:
    container_name: portfolio-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - client

networks:
  webappnetwork:
    driver: bridge
